# -*- coding: utf-8 -*-
"""Copia de Copia de TareaPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZTR1h4wFKnX-AK1JH969tSy2XokGDDUr

De le solución y convierta en código pyton los siguientes problemas. 


1. Escriba una función que calcula el ángulo entre dos vectores.
2. Escriba una función que devuelva los 3 ángulos con respecto a los ejes x, y y z de un vector tridimencional.
3. Escriba una función que calcule el producto vectorial entre dos vectores tridimensionales.
4. Traduzca el diagrama de flujo mostrado en la imagen al lenguaje Python y describa lo que realiza. 
![alt text](http://isapedraza.web.cern.ch/isapedraza/tmpWork/FisicaComputacional/diagrama.png)

5. Diseñar un algoritmo en python que imprima y sume una serie la serie de números 3,6,9,12,...,99
6. Escribir un algoritmo en python que lea cuatro números y que al final escriba el mayor de los cuatro.
7. Diseñar un algorimo  en pytohn para calcular la velocidad (en m/s) de los corredores de la carrera de 1.500 metros. La entrada consistirá en parejas de números (minutos y segundos) que dan el tiempo del corredos; por cada corredor, el algoritmo debe imprimir el tiempo en minutos y segundos, así como la velocidad media. 
  Ejemplo de entrada de datos: (3,53)(3,40)(3,46)(3,52)(4,0)(0,0). El último par de datos se utilizará como fin de entrada de datos. 
 
8. Escribir un algoritmo que calcule la superficie de un triángulo en función de la base y la altura. ($A= 1/2 *Base * Altura$)
 
9. Un sistema de ecuaciones lineales 
 \begin{equation}
ax + by = c
 \end{equation}
\begin{equation}
dx + ey = f
\end{equation}
 
 se puede resolver con las siguientes fórmulas: 
\begin{equation}
x = \frac{ce-bf}{ae-bd}
\end{equation}

\begin{equation}
y = \frac{af-cd}{ae-bd}
\end{equation}


10. Diseñar un programa en Python que lea los dos conjutnos de coeficientes (a,b y c; d,e y f) y visualice los valores de $x$ y $y$. 
 
 11. Diseñe un programa que grafique las siguietes funciones en una misma gráfica. En el rango de -10 a 15. 
 \begin{equation}
f1(x) = 2x^2 + 5x - 2
\end{equation}
\begin{equation}
f2(x) = 4x + 1
\end{equation}
---



---
"""

#Daniel Lima Lopez
#30/08/2017
#Calcular el angulo entre dos vectores

import math
import numpy as np

v1 = np.arange(3)
v2 = np.arange(3)

v1[0] = input("Ingresa v1 x: ")
v1[1] = input("Ingresa v1 y: ")
v1[2] = input("Ingresa v1 z: ")
v2[0] = input("Ingresa v2 x: ")
v2[1] = input("Ingresa v2 y: ")
v2[2] = input("Ingresa v2 z: ")

p = v1 @ v2

mv1 = math.sqrt((v1[0])**2 + v1[1]**2 + v1[2]**2)
mv2 = math.sqrt((v2[0])**2 + v2[1]**2 + v2[2]**2) 

a = math.acos(p / (mv1 * mv2))

print ("El aungulo entre los vectores es", a*180/math.pi)

#Daniel Lima Lopez
#30/08/2017
#Función que devuelva 
#los 3 ángulos con respecto a los ejes x, y y z de un vector tridimencional.

import math
import numpy as np

v = np.arange(3)

v[0] = input("Ingresa v x: ")
v[1] = input("Ingresa v y: ")
v[2] = input("Ingresa v z: ")

mv2 = math.sqrt(v[0]**2 + v[1]**2)
mv3 = math.sqrt(v[0]**2 + v[1]**2 + v[2]**2)
ax = math.acos(v[0]/mv2)
ay = math.asin(v[0]/mv2)
az = math.asin(v[2]/mv3)

print ("El angulo con el eje x es:",ax*180/math.pi)
print ("El angulo con el eje y es:",ay*180/math.pi)
print ("El angulo con el eje z es:",az*180/math.pi)

#Daniel Lima Lopez
#30/08/2017
#Calcular el producto vectorial de dos vectores

import math
import numpy as np

v1 = np.arange(3)
v2 = np.arange(3)
v = np.arange(3)

v1[0] = input("Ingresa v1 x: ")
v1[1] = input("Ingresa v1 y: ")
v1[2] = input("Ingresa v1 z: ")
v2[0] = input("Ingresa v2 x: ")
v2[1] = input("Ingresa v2 y: ")
v2[2] = input("Ingresa v2 z: ")

v[0] = v1[1]*v2[2] - v1[2]*v2[1]
v[1] = -(v1[0]*v2[2] - v1[2]*v2[0])
v[2] = v1[0]*v2[1] - v1[1]*v2[0]

print ("El producto vectorial de v1 X v2 es:", v)

#Daniel Lima Lopez
#30/08/2017
#Diagrama



x = 1

while x<=5:
  if x%3 == 0:
    x = x + 2
  else:
    print (x)
    x = x + 2

#Daniel Lima Lopez
#30/08/2017
#Imprimir y sumar la serie de números 3,6,9,12,...,99

aux = 0

for i in range(1,100):
  if i%3 == 0:
    print (i)
    aux = aux + i

print (aux)

#Daniel Lima Lopez
#30/08/2017
#Leer cuatro números y al final escribir el mayor de los cuatro.

import numpy as np

v = np.arange(4)

for i in range(0,4):
  v[i] = float(input("Ingrese un numero:"))
  
print (v)  


for i in range(0,4):
  aux = 0
  for j in range (0,4):
    if v[j] > v[i]:
      aux = 1
  if aux == 0:
    print ("El numero mayor es:",v[i])
    break

#Daniel Lima Lopez
#30/08/2017
#Calcular la velocidad (en m/s) de los corredores de la carrera de 1.500 metros.
#La entrada consistirá en parejas de números (minutos y segundos) que dan el
#tiempo del corredos; por cada corredor, el algoritmo debe imprimir el tiempo 
#en minutos y segundos, así como la velocidad media. Ejemplo de entrada de 
#datos: (3,53)(3,40)(3,46)(3,52)(4,0)

import numpy as np

print ("Calcular la velocidad (en m/s) de los corredores de la carrera de 1.500 metros")
aux = 0
datos = input("Ingresa las distancias en el formato (m1,s1)(m2,s2)...(mn,sn)")

for i in range(0,len(datos)):
  if datos[i] == '(':
    aux = aux + 1

print ("El numero de corredores es:", aux)
    
datos = datos.replace(')(',' ').replace('(','').replace(')','').replace(',',' ')

m = np.arange(aux)
s = np.arange(aux)
a = np.arange((aux*2+1))
a[aux*2] = len(datos)

aux2 = 0
for i in range (0,len(datos)):
  if datos[i] == ' ':
    a[aux2+1] = i
    aux2 = aux2 + 1
   
maux = 0
saux = 0
auxc = 0
for i in range(0,aux*2):
  n = 0
  r = a[i+1] - auxc
  
  jaux = 0
  for j in range(auxc,a[i+1]):
    
    suma = int(datos[j])*10**(r-jaux-1)
    n = n + suma
    jaux = jaux + 1  
    auxc = a[i+1] + 1
  
  if i%2 == 0:
    m[maux] = n
    maux = maux + 1
  else:
    s[saux] = n
    saux = saux + 1
      
vaux = 0 

for i in range(0,aux):
  print ("El tiempo del corredor", 1+i,"fue de:",m[i],"minutos y",s[i],"segundos")

for i in range(0,aux):
  print ("La velocidad del corredor",1+i,"es:",float(1500/(m[i]*60+s[i])),"m/s")
  vaux = vaux + float(1500/(m[i]*60+s[i]))
  
print ("La velocidad promedio de todos los corredores es:",float(vaux/aux))

#Daniel Lima Lopez
#30/08/2017
#Calcular la superficie de un triángulo en función de la base y la altura

import math

b = input("Introduce la base: ")
a = input("Introduce la altura: ")

ar = (float(a)*float(b)/2)

print ("El area del triangulo es:", ar)

#Daniel Lima Lopez
#30/08/2017
#Lea dos conjutnos de coeficientes (a,b y c; d,e y f) y visualizar los valores de  x y y

print ("ax + by = c")
print ("dx + ey = f")

a = float(input("Ingresa a:"))
b = float(input("Ingresa b:"))
c = float(input("Ingresa c:"))
d = float(input("Ingresa d:"))
e = float(input("Ingresa e:"))
f = float(input("Ingresa f:"))

print ("",a,"X +",b,"Y =",c)
print ("",d,"X +",e,"Y =",f)

print ("X =", (c*e - b*f)/(a*e - b*d))
print ("Y =", (a*f - c*d)/(a*e - b*d))

#Daniel Lima Lopez
#30/08/2017
#Graficar las siguietes funciones en una misma gráfica. En el rango de -10 a 15.
#f1(x) = 2x^2 + 5x - 2
#f2(x) = 4x + 1

import numpy as np
import matplotlib.pyplot as plt

def f1(x):
  im = np.arange(250)
  
  for i in range(0,250):
    im[i] = 2*(x[i])**2 + 5*x[i] - 2
  return im
    
def f2(x):
  im = np.arange(250)
  for i in range(0,250):
    im[i] = 4*x[i] + 1
  return im

x = np.arange(-10.0,15.0,0.1)
y1 = np.arange(-10.0,15.0,0.1)
y2 = np.arange(-10.0,15.0,0.1)

plt.figure(1)
plt.subplot(111)
plt.plot(x,f1(x),x,f2(x))
plt.savefig('Graficas')
plt.show()